# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James A Roland | Wushu x SF Tech
email: james.a.roland@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  James Roland's personal site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
github_username:  jroland81093

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
